name = "MedImagesBenchmark"
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
ArgParse = "1"
HTTP = "1"
JSON3 = "1"
ZipFile = "0.10"
BenchmarkTools = "1"
CUDA = "5"
DataFrames = "1"
CSV = "0.10"
UnicodePlots = "3"
PyCall = "1"
