name = "MedImages"
uuid = "fbff095b-7891-4fc4-b5e5-3cd99b9dd225"
authors = ["Jakub Mitura <jakub.mitura@gmail.com>", "Divyansh Goyal <divital2004@gmail.com>"]
version = "2.0.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ITKIOWrapper = "8538b10a-c1b7-4e8d-b607-b3a5053e6a1f"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Accessors = "0.1.36"
ChainRulesCore = "1.24.0"
ColorTypes = "0.11.5"
Combinatorics = "1.0.2"
CoordinateTransformations = "0.6.3"
Dictionaries = "0.4.2"
HDF5 = "0.17.2"
ITKIOWrapper = "4.0.2"
Interpolations = "0.15.1"
JLD = "0.13.5"
JSON = "0.21.4"
Parameters = "0.12.3"
PyCall = "1.96.4"
Rotations = "1.7.1"
Setfield = "1.1.1"
StaticArrays = "1.4.2"
Statistics = "1.9.0"
julia = "1.10.3"
